# Site
repository: tr3mor/tr3mor.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pavel Storozhenko
title: Senior Site Reliability Engineer
email: storozhenkopf@gmail.com
website: tr3mor.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  tr3mor
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: pavel-storozhenko-94474915a
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm an SRE engineer with more than 7 years of experience working primarily on high-load modern web applications. My passion lies in improving service availability and observability, and I'm always ready to tackle any kind of issue that comes my way.

  I have wide hands-on experience with the following technologies and tools:
  - Clouds: AWS
  - Observability: Grafana, Prometheus, TICK stack, ELK/EFK stack, Jaeger, Sentry, Datadog.
  - Programming languages: Golang, Python.
  - HTTP load balancing: HAProxy, Nginx, Istio, Envoy.
  - Databases: MongoDB, Apache Cassandra.
  - Other: Apache Kafka, Apache Ignite, Redis, RabbitMQ
  - Runtime: Docker, K8s.
  - IaC Tools: Terraform, Packer, Ansible.
  - CI/CD: GitlabCI, GithubActions, Spinnaker, ArgoCD.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Picnic
        link: picnic.app
        link_text: picnic.com
        sub_title: Site Reliability Engineer
        caption: August 2022 - Present
        description: | # this will include new lines to allow paragraphs
          Focused on enhancing the company's observability infrastructure, I specialize in delivering Observability-as-a-Service to developers.
          Proficient in Prometheus, Grafana, Datadog, and automation, I manage these systems on AWS in K8s.
      - layout: left
        title: Tinkoff Bank
        link: tinkoff.ru
        link_text: tinkoff.ru
        sub_title: Site Reliability Engineer
        caption: June 2021 - July 2022
        description: | # this will include new lines to allow paragraphs
          Led the development of an Internal Developers Platform for company-wide use, overseeing the design of monitoring, logging, and tracing requirements. 
          Implemented Observability as a Service using Prometheus, Grafana, Jaeger, and the ELK stack. Utilized K8s as the primary runtime platform, ensuring the deployment of production-critical workloads adhered to best practices for high availability.
      - layout: left
        title: DINS
        sub_title: SysOPS/Site Reliability Engineer
        caption: December 2016 - June 2021
        description: | # this will include new lines to allow paragraphs
          Enhancing a platform with 300+ microservices, I've contributed to achieving a target availability of 99.99%. 
          Led the planning and execution of a seamless migration from on-premises to AWS, ensuring zero downtime.
      - layout: left
        title: Tikkurila
        sub_title: Tech Analyst
        caption: December 2015 - December 2016
      - layout: left
        title: TTK
        sub_title: Technical Support Specialist
        caption: October 2014 - December 2015

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Personal infra
        link: github.com/tr3mor/personal-infra
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
        description: | # this will include new lines to allow paragraphs
          
          This repo implements GitOps approach to manage my personal infra. Built using Terraform Cloud, Github Actions, ArgoCD, and Terratest.

      - layout: top-middle
        title: Rest Mock
        link: github.com/tr3mor/restmock
        # link_text: Project Website
        #        additional_links:
        #          - title:  sproogen/modern-resume-theme
        #            icon: fab fa-github
        #            url: github.com/sproogen/modern-resume-theme
        #          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #          #   icon: fab fa-github
        #          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #        quote: >
        description: | # this will include new lines to allow paragraphs
          Simple Go application which can mock any HTTP response. Useful for Ingress rule troubleshooting.

      - layout: top-middle
        title: Prober
        link: github.com/tr3mor/prober
        # link_text: Project Website
        #        additional_links:
        #          - title:  sproogen/modern-resume-theme
        #            icon: fab fa-github
        #            url: github.com/sproogen/modern-resume-theme
        #          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #          #   icon: fab fa-github
        #          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #        quote: >
        description: | # this will include new lines to allow paragraphs
          Simple prober codebase which could be easily extended with any custom probe. Could be used when blackbox-exporter functionality is not enough.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Southern Federal University, Rostov-on-Don, Russia
        caption: 2008 - 2013
        sub_title: Specialist Degree in High Technologies

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
